version: '3.8'

services:
  web:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./templates:/var/www/html
    depends_on:
      - db
    networks:
      - my_network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - my_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
    volumes:
      - ./initdb/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

